// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT0P8BU-eoWl_TsrZ0dFfSBMKMi0ub93E',
    appId: '1:647800686217:web:b208634d07204254bd6858',
    messagingSenderId: '647800686217',
    projectId: 'todo-flutter-448af',
    authDomain: 'todo-flutter-448af.firebaseapp.com',
    databaseURL: 'https://todo-flutter-448af-default-rtdb.firebaseio.com',
    storageBucket: 'todo-flutter-448af.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNMAvmDkDJjdSBUWw6kkNptgdrG2OFvhg',
    appId: '1:647800686217:android:1297e563deedacb6bd6858',
    messagingSenderId: '647800686217',
    projectId: 'todo-flutter-448af',
    databaseURL: 'https://todo-flutter-448af-default-rtdb.firebaseio.com',
    storageBucket: 'todo-flutter-448af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0OKKnj2xrgJ7MI-LNdaNNC9lvq9wY4FI',
    appId: '1:647800686217:ios:4ca0b3e80592ca77bd6858',
    messagingSenderId: '647800686217',
    projectId: 'todo-flutter-448af',
    databaseURL: 'https://todo-flutter-448af-default-rtdb.firebaseio.com',
    storageBucket: 'todo-flutter-448af.appspot.com',
    iosBundleId: 'com.tech_attom.flutterTodoPos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0OKKnj2xrgJ7MI-LNdaNNC9lvq9wY4FI',
    appId: '1:647800686217:ios:598ad3568fabc251bd6858',
    messagingSenderId: '647800686217',
    projectId: 'todo-flutter-448af',
    databaseURL: 'https://todo-flutter-448af-default-rtdb.firebaseio.com',
    storageBucket: 'todo-flutter-448af.appspot.com',
    iosBundleId: 'com.tech_attom.flutterTodoPos.RunnerTests',
  );
}
